{{- if or .Values.secrets.pgDsn .Values.secrets.s3AccessKey .Values.secrets.s3SecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-freezer.fullname" . }}-secrets
  labels:
    {{- include "pg-freezer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.pgDsn }}
  PG_DSN: {{ .Values.secrets.pgDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.s3SecretKey }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  {{- end }}
{{- end }}
